# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hbadr
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: chatbot
    ports:
      - 5432:5432
      